import json
import os

from app.config import (
    CIRQ_CIRCUIT_ARTIFACT,
    CIRQ_CONVERGENCE_ARTIFACT,
    DATA_DIR,
    LOG_FILE,
    QISKIT_ARTIFACT,
    SCENARIOS_JSON,
)

class FileService:
    @staticmethod
    def read_scenarios():
        try:
            if not os.path.exists(SCENARIOS_JSON):
                return []
            with open(SCENARIOS_JSON, "r", encoding="utf-8") as scenario_file:
                return json.load(scenario_file)
        except Exception as error:
            print(f"Error loading scenarios: {error}")
            return []

    @staticmethod
    def read_logs():
        try:
            if not os.path.exists(LOG_FILE):
                return "Waiting for first execution..."
            with open(LOG_FILE, "r", encoding="utf-8") as log_file:
                lines = log_file.readlines()
                return "".join(reversed(lines))
        except Exception:
            return "Error reading logs."

    @staticmethod
    def append_log(message: str):
        try:
            with open(LOG_FILE, "a", encoding="utf-8") as log_file:
                log_file.write(message)
        except Exception as error:
            print(f"Error appending log: {error}")

    @staticmethod
    def clear_artifact_files():
        """Delete artifacts generated by the previous adaptation cycle."""
        files_to_remove = [
            QISKIT_ARTIFACT,
            CIRQ_CIRCUIT_ARTIFACT,
            CIRQ_CONVERGENCE_ARTIFACT,
        ]
        
        print("Removing artifacts from the previous adaptation cycle.")
        for filename in files_to_remove:
            file_path = os.path.join(DATA_DIR, filename)
            if os.path.exists(file_path):
                try:
                    os.remove(file_path)
                except Exception as error:
                    print(f"Could not remove artifact {filename}: {error}")

    @staticmethod
    def get_artifact_path():
        """Return the URL of the available quantum artifact, if any."""
        if os.path.exists(os.path.join(DATA_DIR, QISKIT_ARTIFACT)):
            return f"/api/static/{QISKIT_ARTIFACT}"
        if os.path.exists(os.path.join(DATA_DIR, CIRQ_CIRCUIT_ARTIFACT)):
            return f"/api/static/{CIRQ_CIRCUIT_ARTIFACT}"
        if os.path.exists(os.path.join(DATA_DIR, CIRQ_CONVERGENCE_ARTIFACT)):
            return f"/api/static/{CIRQ_CONVERGENCE_ARTIFACT}"
        return None
